### ISSUE TITLE
TypeError: Cannot read property 'groups' of null

### ISSUE THREAD

**Issue by trivikr** [bcoe/istheshipstillstuck#3]
```console
$ node -v
v14.15.4

$ npm --version
7.5.3

$ npx istheshipstillstuck           
file:///Users/trivikr/.npm/_npx/3b3fba396e57214c/node_modules/istheshipstillstuck/index.mjs:13
  console.info(match.groups.answer)
                     ^

TypeError: Cannot read property 'groups' of null
    at file:///Users/trivikr/.npm/_npx/3b3fba396e57214c/node_modules/istheshipstillstuck/index.mjs:13:22
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code 1
npm ERR! path /Users/trivikr/workspace/AwsJavaScriptSdkRelease
npm ERR! command failed
npm ERR! command sh -c istheshipstillstuck

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trivikr/.npm/_logs/2021-03-29T04_02_24_176Z-debug.log
```

**Comment by trivikr** [comment]
This error is thrown as the structure of the website https://istheshipstillstuck.com/ has changed, as ship is now unstuck.
